### ISSUE TITLE
Bug de lumière en Créatif

### ISSUE THREAD

**Issue by DRAKAAAA** [Over2Craft-mc/community#11]
Beaucoup de bug de lumière en créatif, dès qu'un utilise worldedit ou voxel sniper

**Comment by Over2Craft-mc** [comment]
Normalement c'est corrigé. Est-ce que tu pourrais vérifier qu'il n'y a pas de lags (voire serveur) client quand tu utilises we ou voxel ?

**Comment by DRAKAAAA** [comment]
J'ai pas remarqué de lag, mais les bugs de lumières sont encore présents (peut être plus après un reboot?)
