### ISSUE TITLE
Créatif : /plots merge

### ISSUE THREAD

**Issue by DRAKAAAA** [Over2Craft-mc/community#15]
J'ai essayé de /plot merge deux plot 50 adjacents, et reçois ce message : 

![2021-01-18_16 51 54](https://user-images.githubusercontent.com/77589302/104937352-f2a44c00-59ad-11eb-92ca-9d606ff04ec2.png)

Les deux parcelles sont bien à côté, et je regardais bien dans la bonne direction

**Comment by Over2Craft-mc** [comment]
Tu as claim la deuxième parcelle d'abord ?

**Comment by DRAKAAAA** [comment]
J'ai claims les deux parcelles
