### ISSUE TITLE
Super Magical Box - Potion interdite

### ISSUE THREAD

**Issue by gwazed** [Over2Craft-mc/community#25]
La potion n'est plus give dû au plugin Illegalitem

C'est une potion custom avec plein d'effet. C'est la console qui l'a give normalement

**Comment by gwazed** [comment]
![image](https://user-images.githubusercontent.com/75589114/105176495-9e23dc80-5b25-11eb-8c85-6be46f79eea5.png)

**Comment by Over2Craft-mc** [comment]
A tester au prochain rebot

**Comment by Over2Craft-mc** [comment]
Est-ce que c'est bon ?
