### ISSUE TITLE
Nouvelle bannière 

### ISSUE THREAD

**Issue by Over2Craft-mc** [Over2Craft-mc/community#32]
Nouvelle bannière pour https://www.serveurs-minecraft.org/vote.php?id=9107 (pour remplacer https://www.over2craft.com/assets/images/apercu2.png)

Quelques éléments utiles https://cdn.discordapp.com/attachments/347472493625475072/776589492546568252/02C.zip
https://fs.over2craft.com/server-icon.png

**Comment by Over2Craft-mc** [comment]
@Alexisdepris du neuf ? Ce serait bien de l'avoir avant le 01/02. On a 30 jours de pub à partir de cette date

**Comment by Alexisdepris** [comment]
Oui désolé, je m'y met de suite.

**Comment by Over2Craft-mc** [comment]
En attendant j'ai remplacé 
![image](https://user-images.githubusercontent.com/74878280/105639072-78287000-5e76-11eb-8cad-44823cbeb749.png)
par 
![image](https://user-images.githubusercontent.com/74878280/105639080-7e1e5100-5e76-11eb-9cf9-e669461de3de.png)
